GET http://localhost:3001/api/users/

###
POST http://localhost:3001/api/users/
content-type: application/json

{
		"username": "paul",
		"name": "Paul Allen",
		"password": "watermark"
}

###
DELETE http://localhost:3001/api/users/642a74baedbb590e2a5c19f1