GET http://localhost:3001/api/blogs/

###
DELETE http://localhost:3001/api/blogs/:id

###
POST http://localhost:3001/api/blogs/
content-type: application/json

{
	"title": "Intro to Full Stack",
  "author": "F.S. Open",
  "url": "https://fullstackopen.com",
  "likes": 2
}

###
PUT http://localhost:3001/api/blogs/6428d7b4cf73da50631da441
content-type: application/json

{
  "title": "Intro to Full Stack",
  "author": "F.S. Open",
  "url": "https://fullstackopen.com",
  "likes": 3
}