GET http://localhost:3001/api/blogs/

###
DELETE http://localhost:3001/api/blogs/642a15a2c38047014664d63b

###
POST http://localhost:3001/api/blogs/
content-type: application/json

{
	"title": "Intro to Full Stack",
  "author": "F.S. Open",
  "url": "https://fullstackopen.com",
  "likes": 2,
  "userId": "642a1597c38047014664d635"
}

###
PUT http://localhost:3001/api/blogs/:id
content-type: application/json

{
  "title": "Intro to Full Stack",
  "author": "F.S. Open",
  "url": "https://fullstackopen.com",
  "likes": 3
}